title: "Francisco Neves"
author: "Francisco Neves"
description: "Francisco Neves, 2024" 
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false            # use a dark header

# Menu

navigation:   # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About Me"}
  - {url: "https://docs.google.com/document/d/1UlXyave9EUw-omKExQYvnqJst0uIZwbp/edit?usp=sharing&ouid=110779932187320308482&rtpof=true&sd=true", title: "CV"}
  - {url: "https://fdscn.substack.com", title: "Newsletter"}
  - {file: "ibeb.md", title: "Resources"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Goodreads, icon: goodreads, url: "https://www.goodreads.com/user/show/96137929-francisco-neves"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/franciscodscn/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/fdscneves"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
