title: "Francisco Neves"
author: "Francisco Neves"
description: "Erasmus Universiteit Rotterdam" 
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false            # use a dark header

# Menu

navigation:   # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About Me"}
  - {file: "/francisco.pdf", title: "CV"}
  - {url: "https://fdscn.substack.com", title: "Newsletter"}
  - {file: "ibeb.md", title: "IBEB"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:598499fd@eur.nl"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/franciscodscn/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/fdscneves"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
